# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- script: |
    composer run post-root-package-install
  displayName: 'composer post root install'
- script: |
    php artisan key:generate
  displayName: 'Generate key'
- script: |
    vendor/bin/phpunit --log-junit tests/Results/TEST-phpunit-junit.xml
  displayName: 'Running Unit Tests'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(system.defaultWorkingDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1